version: '3.8'

services:
  fastapi:
    build: .
    container_name: qr_code_api
    volumes:
      - ./qr_codes:/app/qr_codes # Maps ./qr_codes from your host to /app/qr_codes in the container
      - ./:/myapp/
    environment:
      - QR_CODE_DIR=/app/qr_codes
      - FILL_COLOR=black
      - BACK_COLOR=white
      - SERVER_BASE_URL=http://localhost
    networks:
      - qr_network

  nginx:
    image: nginx:latest
    container_name: qr_code_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./qr_codes:/var/www/qr_codes # Maps ./qr_codes from your host to /var/www/qr_codes in the container
    depends_on:
      - fastapi
    networks:
      - qr_network

networks:
  qr_network:
    driver: bridge
